version: "3"

services:
  #PHP Service
  arcoirsl-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: arcoirsl/php
    container_name: arcoirsl-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - arcoirsl-network

  #Nginx Service
  arcoirsl-webserver:
    image: nginx:alpine
    container_name: arcoirsl-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - arcoirsl-network

  #MySQL Service
  arcoirsl-db:
    image: mysql:8.0.31
    container_name: arcoirsl-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - arcoirsl-network

  # MailHog Service
  arcoirsl-mail:
    image: mailhog/mailhog:v1.0.1
    container_name: arcoirsl-mail
    restart: unless-stopped
    tty: true
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - arcoirsl-network

#Docker Networks
networks:
  arcoirsl-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
